
name: 'conda-pack for lcls rhel6'
description: 'Execute conda-pack in rhel6'
author: 'jacquelinegarrahan'
runs:
  using: 'composite'
  steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Build docker
      uses: docker-practice/actions-setup-docker@master
    - name: Pack environment
      run: |
        set -x
        docker run -v $(pwd)/environment.yml:/tmp/environment.yml \
        -v $(pwd):/tmp/project \
        -e ENVIRONMENT_NAME=${{ env.ENVIRONMENT_NAME }} --name build-env  -t jgarrahan/conda-pack-centos6:v0.0 /tmp/environment.yml
      shell: bash
    - name: Copy environment
      run: |
        set -x 
        docker cp build-env:/root/${{ env.ENVIRONMENT_NAME }}.tar.gz .
      shell: bash
